// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package getipranges

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetIPRanges(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetIPRangesResult, error) {
	var rv GetIPRangesResult
	err := ctx.Invoke("github:index/getipranges/getIPRanges:getIPRanges", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getIPRanges.
type GetIPRangesResult struct {
	// An Array of IP addresses in CIDR format specifying the Git servers.
	Gits []string `pulumi:"gits"`
	// An Array of IP addresses in CIDR format specifying the addresses that incoming service hooks will originate from.
	Hooks []string `pulumi:"hooks"`
	// id is the provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// An Array of IP addresses in CIDR format specifying the A records for GitHub Importer.
	Importers []string `pulumi:"importers"`
	// An Array of IP addresses in CIDR format specifying the A records for GitHub Pages.
	Pages []string `pulumi:"pages"`
}
