// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package github

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type BranchProtectionRequiredPullRequestReviews struct {
	DismissStaleReviews          *bool    `pulumi:"dismissStaleReviews"`
	DismissalTeams               []string `pulumi:"dismissalTeams"`
	DismissalUsers               []string `pulumi:"dismissalUsers"`
	IncludeAdmins                *bool    `pulumi:"includeAdmins"`
	RequireCodeOwnerReviews      *bool    `pulumi:"requireCodeOwnerReviews"`
	RequiredApprovingReviewCount *int     `pulumi:"requiredApprovingReviewCount"`
}

// BranchProtectionRequiredPullRequestReviewsInput is an input type that accepts BranchProtectionRequiredPullRequestReviewsArgs and BranchProtectionRequiredPullRequestReviewsOutput values.
// You can construct a concrete instance of `BranchProtectionRequiredPullRequestReviewsInput` via:
//
// 		 BranchProtectionRequiredPullRequestReviewsArgs{...}
//
type BranchProtectionRequiredPullRequestReviewsInput interface {
	pulumi.Input

	ToBranchProtectionRequiredPullRequestReviewsOutput() BranchProtectionRequiredPullRequestReviewsOutput
	ToBranchProtectionRequiredPullRequestReviewsOutputWithContext(context.Context) BranchProtectionRequiredPullRequestReviewsOutput
}

type BranchProtectionRequiredPullRequestReviewsArgs struct {
	DismissStaleReviews          pulumi.BoolPtrInput     `pulumi:"dismissStaleReviews"`
	DismissalTeams               pulumi.StringArrayInput `pulumi:"dismissalTeams"`
	DismissalUsers               pulumi.StringArrayInput `pulumi:"dismissalUsers"`
	IncludeAdmins                pulumi.BoolPtrInput     `pulumi:"includeAdmins"`
	RequireCodeOwnerReviews      pulumi.BoolPtrInput     `pulumi:"requireCodeOwnerReviews"`
	RequiredApprovingReviewCount pulumi.IntPtrInput      `pulumi:"requiredApprovingReviewCount"`
}

func (BranchProtectionRequiredPullRequestReviewsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchProtectionRequiredPullRequestReviews)(nil)).Elem()
}

func (i BranchProtectionRequiredPullRequestReviewsArgs) ToBranchProtectionRequiredPullRequestReviewsOutput() BranchProtectionRequiredPullRequestReviewsOutput {
	return i.ToBranchProtectionRequiredPullRequestReviewsOutputWithContext(context.Background())
}

func (i BranchProtectionRequiredPullRequestReviewsArgs) ToBranchProtectionRequiredPullRequestReviewsOutputWithContext(ctx context.Context) BranchProtectionRequiredPullRequestReviewsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRequiredPullRequestReviewsOutput)
}

func (i BranchProtectionRequiredPullRequestReviewsArgs) ToBranchProtectionRequiredPullRequestReviewsPtrOutput() BranchProtectionRequiredPullRequestReviewsPtrOutput {
	return i.ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(context.Background())
}

func (i BranchProtectionRequiredPullRequestReviewsArgs) ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(ctx context.Context) BranchProtectionRequiredPullRequestReviewsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRequiredPullRequestReviewsOutput).ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(ctx)
}

// BranchProtectionRequiredPullRequestReviewsPtrInput is an input type that accepts BranchProtectionRequiredPullRequestReviewsArgs, BranchProtectionRequiredPullRequestReviewsPtr and BranchProtectionRequiredPullRequestReviewsPtrOutput values.
// You can construct a concrete instance of `BranchProtectionRequiredPullRequestReviewsPtrInput` via:
//
// 		 BranchProtectionRequiredPullRequestReviewsArgs{...}
//
//  or:
//
// 		 nil
//
type BranchProtectionRequiredPullRequestReviewsPtrInput interface {
	pulumi.Input

	ToBranchProtectionRequiredPullRequestReviewsPtrOutput() BranchProtectionRequiredPullRequestReviewsPtrOutput
	ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(context.Context) BranchProtectionRequiredPullRequestReviewsPtrOutput
}

type branchProtectionRequiredPullRequestReviewsPtrType BranchProtectionRequiredPullRequestReviewsArgs

func BranchProtectionRequiredPullRequestReviewsPtr(v *BranchProtectionRequiredPullRequestReviewsArgs) BranchProtectionRequiredPullRequestReviewsPtrInput {
	return (*branchProtectionRequiredPullRequestReviewsPtrType)(v)
}

func (*branchProtectionRequiredPullRequestReviewsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchProtectionRequiredPullRequestReviews)(nil)).Elem()
}

func (i *branchProtectionRequiredPullRequestReviewsPtrType) ToBranchProtectionRequiredPullRequestReviewsPtrOutput() BranchProtectionRequiredPullRequestReviewsPtrOutput {
	return i.ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(context.Background())
}

func (i *branchProtectionRequiredPullRequestReviewsPtrType) ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(ctx context.Context) BranchProtectionRequiredPullRequestReviewsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRequiredPullRequestReviewsPtrOutput)
}

type BranchProtectionRequiredPullRequestReviewsOutput struct{ *pulumi.OutputState }

func (BranchProtectionRequiredPullRequestReviewsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchProtectionRequiredPullRequestReviews)(nil)).Elem()
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) ToBranchProtectionRequiredPullRequestReviewsOutput() BranchProtectionRequiredPullRequestReviewsOutput {
	return o
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) ToBranchProtectionRequiredPullRequestReviewsOutputWithContext(ctx context.Context) BranchProtectionRequiredPullRequestReviewsOutput {
	return o
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) ToBranchProtectionRequiredPullRequestReviewsPtrOutput() BranchProtectionRequiredPullRequestReviewsPtrOutput {
	return o.ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(context.Background())
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(ctx context.Context) BranchProtectionRequiredPullRequestReviewsPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *BranchProtectionRequiredPullRequestReviews {
		return &v
	}).(BranchProtectionRequiredPullRequestReviewsPtrOutput)
}
func (o BranchProtectionRequiredPullRequestReviewsOutput) DismissStaleReviews() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *bool { return v.DismissStaleReviews }).(pulumi.BoolPtrOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) DismissalTeams() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) []string { return v.DismissalTeams }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) DismissalUsers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) []string { return v.DismissalUsers }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) IncludeAdmins() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *bool { return v.IncludeAdmins }).(pulumi.BoolPtrOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) RequireCodeOwnerReviews() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *bool { return v.RequireCodeOwnerReviews }).(pulumi.BoolPtrOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsOutput) RequiredApprovingReviewCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *int { return v.RequiredApprovingReviewCount }).(pulumi.IntPtrOutput)
}

type BranchProtectionRequiredPullRequestReviewsPtrOutput struct{ *pulumi.OutputState }

func (BranchProtectionRequiredPullRequestReviewsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchProtectionRequiredPullRequestReviews)(nil)).Elem()
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) ToBranchProtectionRequiredPullRequestReviewsPtrOutput() BranchProtectionRequiredPullRequestReviewsPtrOutput {
	return o
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) ToBranchProtectionRequiredPullRequestReviewsPtrOutputWithContext(ctx context.Context) BranchProtectionRequiredPullRequestReviewsPtrOutput {
	return o
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) Elem() BranchProtectionRequiredPullRequestReviewsOutput {
	return o.ApplyT(func(v *BranchProtectionRequiredPullRequestReviews) BranchProtectionRequiredPullRequestReviews {
		return *v
	}).(BranchProtectionRequiredPullRequestReviewsOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) DismissStaleReviews() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *bool { return v.DismissStaleReviews }).(pulumi.BoolPtrOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) DismissalTeams() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) []string { return v.DismissalTeams }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) DismissalUsers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) []string { return v.DismissalUsers }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) IncludeAdmins() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *bool { return v.IncludeAdmins }).(pulumi.BoolPtrOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) RequireCodeOwnerReviews() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *bool { return v.RequireCodeOwnerReviews }).(pulumi.BoolPtrOutput)
}

func (o BranchProtectionRequiredPullRequestReviewsPtrOutput) RequiredApprovingReviewCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredPullRequestReviews) *int { return v.RequiredApprovingReviewCount }).(pulumi.IntPtrOutput)
}

type BranchProtectionRequiredStatusChecks struct {
	Contexts      []string `pulumi:"contexts"`
	IncludeAdmins *bool    `pulumi:"includeAdmins"`
	Strict        *bool    `pulumi:"strict"`
}

// BranchProtectionRequiredStatusChecksInput is an input type that accepts BranchProtectionRequiredStatusChecksArgs and BranchProtectionRequiredStatusChecksOutput values.
// You can construct a concrete instance of `BranchProtectionRequiredStatusChecksInput` via:
//
// 		 BranchProtectionRequiredStatusChecksArgs{...}
//
type BranchProtectionRequiredStatusChecksInput interface {
	pulumi.Input

	ToBranchProtectionRequiredStatusChecksOutput() BranchProtectionRequiredStatusChecksOutput
	ToBranchProtectionRequiredStatusChecksOutputWithContext(context.Context) BranchProtectionRequiredStatusChecksOutput
}

type BranchProtectionRequiredStatusChecksArgs struct {
	Contexts      pulumi.StringArrayInput `pulumi:"contexts"`
	IncludeAdmins pulumi.BoolPtrInput     `pulumi:"includeAdmins"`
	Strict        pulumi.BoolPtrInput     `pulumi:"strict"`
}

func (BranchProtectionRequiredStatusChecksArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchProtectionRequiredStatusChecks)(nil)).Elem()
}

func (i BranchProtectionRequiredStatusChecksArgs) ToBranchProtectionRequiredStatusChecksOutput() BranchProtectionRequiredStatusChecksOutput {
	return i.ToBranchProtectionRequiredStatusChecksOutputWithContext(context.Background())
}

func (i BranchProtectionRequiredStatusChecksArgs) ToBranchProtectionRequiredStatusChecksOutputWithContext(ctx context.Context) BranchProtectionRequiredStatusChecksOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRequiredStatusChecksOutput)
}

func (i BranchProtectionRequiredStatusChecksArgs) ToBranchProtectionRequiredStatusChecksPtrOutput() BranchProtectionRequiredStatusChecksPtrOutput {
	return i.ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(context.Background())
}

func (i BranchProtectionRequiredStatusChecksArgs) ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(ctx context.Context) BranchProtectionRequiredStatusChecksPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRequiredStatusChecksOutput).ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(ctx)
}

// BranchProtectionRequiredStatusChecksPtrInput is an input type that accepts BranchProtectionRequiredStatusChecksArgs, BranchProtectionRequiredStatusChecksPtr and BranchProtectionRequiredStatusChecksPtrOutput values.
// You can construct a concrete instance of `BranchProtectionRequiredStatusChecksPtrInput` via:
//
// 		 BranchProtectionRequiredStatusChecksArgs{...}
//
//  or:
//
// 		 nil
//
type BranchProtectionRequiredStatusChecksPtrInput interface {
	pulumi.Input

	ToBranchProtectionRequiredStatusChecksPtrOutput() BranchProtectionRequiredStatusChecksPtrOutput
	ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(context.Context) BranchProtectionRequiredStatusChecksPtrOutput
}

type branchProtectionRequiredStatusChecksPtrType BranchProtectionRequiredStatusChecksArgs

func BranchProtectionRequiredStatusChecksPtr(v *BranchProtectionRequiredStatusChecksArgs) BranchProtectionRequiredStatusChecksPtrInput {
	return (*branchProtectionRequiredStatusChecksPtrType)(v)
}

func (*branchProtectionRequiredStatusChecksPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchProtectionRequiredStatusChecks)(nil)).Elem()
}

func (i *branchProtectionRequiredStatusChecksPtrType) ToBranchProtectionRequiredStatusChecksPtrOutput() BranchProtectionRequiredStatusChecksPtrOutput {
	return i.ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(context.Background())
}

func (i *branchProtectionRequiredStatusChecksPtrType) ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(ctx context.Context) BranchProtectionRequiredStatusChecksPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRequiredStatusChecksPtrOutput)
}

type BranchProtectionRequiredStatusChecksOutput struct{ *pulumi.OutputState }

func (BranchProtectionRequiredStatusChecksOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchProtectionRequiredStatusChecks)(nil)).Elem()
}

func (o BranchProtectionRequiredStatusChecksOutput) ToBranchProtectionRequiredStatusChecksOutput() BranchProtectionRequiredStatusChecksOutput {
	return o
}

func (o BranchProtectionRequiredStatusChecksOutput) ToBranchProtectionRequiredStatusChecksOutputWithContext(ctx context.Context) BranchProtectionRequiredStatusChecksOutput {
	return o
}

func (o BranchProtectionRequiredStatusChecksOutput) ToBranchProtectionRequiredStatusChecksPtrOutput() BranchProtectionRequiredStatusChecksPtrOutput {
	return o.ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(context.Background())
}

func (o BranchProtectionRequiredStatusChecksOutput) ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(ctx context.Context) BranchProtectionRequiredStatusChecksPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredStatusChecks) *BranchProtectionRequiredStatusChecks {
		return &v
	}).(BranchProtectionRequiredStatusChecksPtrOutput)
}
func (o BranchProtectionRequiredStatusChecksOutput) Contexts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRequiredStatusChecks) []string { return v.Contexts }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRequiredStatusChecksOutput) IncludeAdmins() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredStatusChecks) *bool { return v.IncludeAdmins }).(pulumi.BoolPtrOutput)
}

func (o BranchProtectionRequiredStatusChecksOutput) Strict() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredStatusChecks) *bool { return v.Strict }).(pulumi.BoolPtrOutput)
}

type BranchProtectionRequiredStatusChecksPtrOutput struct{ *pulumi.OutputState }

func (BranchProtectionRequiredStatusChecksPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchProtectionRequiredStatusChecks)(nil)).Elem()
}

func (o BranchProtectionRequiredStatusChecksPtrOutput) ToBranchProtectionRequiredStatusChecksPtrOutput() BranchProtectionRequiredStatusChecksPtrOutput {
	return o
}

func (o BranchProtectionRequiredStatusChecksPtrOutput) ToBranchProtectionRequiredStatusChecksPtrOutputWithContext(ctx context.Context) BranchProtectionRequiredStatusChecksPtrOutput {
	return o
}

func (o BranchProtectionRequiredStatusChecksPtrOutput) Elem() BranchProtectionRequiredStatusChecksOutput {
	return o.ApplyT(func(v *BranchProtectionRequiredStatusChecks) BranchProtectionRequiredStatusChecks { return *v }).(BranchProtectionRequiredStatusChecksOutput)
}

func (o BranchProtectionRequiredStatusChecksPtrOutput) Contexts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRequiredStatusChecks) []string { return v.Contexts }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRequiredStatusChecksPtrOutput) IncludeAdmins() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredStatusChecks) *bool { return v.IncludeAdmins }).(pulumi.BoolPtrOutput)
}

func (o BranchProtectionRequiredStatusChecksPtrOutput) Strict() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v BranchProtectionRequiredStatusChecks) *bool { return v.Strict }).(pulumi.BoolPtrOutput)
}

type BranchProtectionRestrictions struct {
	Apps  []string `pulumi:"apps"`
	Teams []string `pulumi:"teams"`
	Users []string `pulumi:"users"`
}

// BranchProtectionRestrictionsInput is an input type that accepts BranchProtectionRestrictionsArgs and BranchProtectionRestrictionsOutput values.
// You can construct a concrete instance of `BranchProtectionRestrictionsInput` via:
//
// 		 BranchProtectionRestrictionsArgs{...}
//
type BranchProtectionRestrictionsInput interface {
	pulumi.Input

	ToBranchProtectionRestrictionsOutput() BranchProtectionRestrictionsOutput
	ToBranchProtectionRestrictionsOutputWithContext(context.Context) BranchProtectionRestrictionsOutput
}

type BranchProtectionRestrictionsArgs struct {
	Apps  pulumi.StringArrayInput `pulumi:"apps"`
	Teams pulumi.StringArrayInput `pulumi:"teams"`
	Users pulumi.StringArrayInput `pulumi:"users"`
}

func (BranchProtectionRestrictionsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchProtectionRestrictions)(nil)).Elem()
}

func (i BranchProtectionRestrictionsArgs) ToBranchProtectionRestrictionsOutput() BranchProtectionRestrictionsOutput {
	return i.ToBranchProtectionRestrictionsOutputWithContext(context.Background())
}

func (i BranchProtectionRestrictionsArgs) ToBranchProtectionRestrictionsOutputWithContext(ctx context.Context) BranchProtectionRestrictionsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRestrictionsOutput)
}

func (i BranchProtectionRestrictionsArgs) ToBranchProtectionRestrictionsPtrOutput() BranchProtectionRestrictionsPtrOutput {
	return i.ToBranchProtectionRestrictionsPtrOutputWithContext(context.Background())
}

func (i BranchProtectionRestrictionsArgs) ToBranchProtectionRestrictionsPtrOutputWithContext(ctx context.Context) BranchProtectionRestrictionsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRestrictionsOutput).ToBranchProtectionRestrictionsPtrOutputWithContext(ctx)
}

// BranchProtectionRestrictionsPtrInput is an input type that accepts BranchProtectionRestrictionsArgs, BranchProtectionRestrictionsPtr and BranchProtectionRestrictionsPtrOutput values.
// You can construct a concrete instance of `BranchProtectionRestrictionsPtrInput` via:
//
// 		 BranchProtectionRestrictionsArgs{...}
//
//  or:
//
// 		 nil
//
type BranchProtectionRestrictionsPtrInput interface {
	pulumi.Input

	ToBranchProtectionRestrictionsPtrOutput() BranchProtectionRestrictionsPtrOutput
	ToBranchProtectionRestrictionsPtrOutputWithContext(context.Context) BranchProtectionRestrictionsPtrOutput
}

type branchProtectionRestrictionsPtrType BranchProtectionRestrictionsArgs

func BranchProtectionRestrictionsPtr(v *BranchProtectionRestrictionsArgs) BranchProtectionRestrictionsPtrInput {
	return (*branchProtectionRestrictionsPtrType)(v)
}

func (*branchProtectionRestrictionsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchProtectionRestrictions)(nil)).Elem()
}

func (i *branchProtectionRestrictionsPtrType) ToBranchProtectionRestrictionsPtrOutput() BranchProtectionRestrictionsPtrOutput {
	return i.ToBranchProtectionRestrictionsPtrOutputWithContext(context.Background())
}

func (i *branchProtectionRestrictionsPtrType) ToBranchProtectionRestrictionsPtrOutputWithContext(ctx context.Context) BranchProtectionRestrictionsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchProtectionRestrictionsPtrOutput)
}

type BranchProtectionRestrictionsOutput struct{ *pulumi.OutputState }

func (BranchProtectionRestrictionsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchProtectionRestrictions)(nil)).Elem()
}

func (o BranchProtectionRestrictionsOutput) ToBranchProtectionRestrictionsOutput() BranchProtectionRestrictionsOutput {
	return o
}

func (o BranchProtectionRestrictionsOutput) ToBranchProtectionRestrictionsOutputWithContext(ctx context.Context) BranchProtectionRestrictionsOutput {
	return o
}

func (o BranchProtectionRestrictionsOutput) ToBranchProtectionRestrictionsPtrOutput() BranchProtectionRestrictionsPtrOutput {
	return o.ToBranchProtectionRestrictionsPtrOutputWithContext(context.Background())
}

func (o BranchProtectionRestrictionsOutput) ToBranchProtectionRestrictionsPtrOutputWithContext(ctx context.Context) BranchProtectionRestrictionsPtrOutput {
	return o.ApplyT(func(v BranchProtectionRestrictions) *BranchProtectionRestrictions {
		return &v
	}).(BranchProtectionRestrictionsPtrOutput)
}
func (o BranchProtectionRestrictionsOutput) Apps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRestrictions) []string { return v.Apps }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRestrictionsOutput) Teams() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRestrictions) []string { return v.Teams }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRestrictionsOutput) Users() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRestrictions) []string { return v.Users }).(pulumi.StringArrayOutput)
}

type BranchProtectionRestrictionsPtrOutput struct{ *pulumi.OutputState }

func (BranchProtectionRestrictionsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchProtectionRestrictions)(nil)).Elem()
}

func (o BranchProtectionRestrictionsPtrOutput) ToBranchProtectionRestrictionsPtrOutput() BranchProtectionRestrictionsPtrOutput {
	return o
}

func (o BranchProtectionRestrictionsPtrOutput) ToBranchProtectionRestrictionsPtrOutputWithContext(ctx context.Context) BranchProtectionRestrictionsPtrOutput {
	return o
}

func (o BranchProtectionRestrictionsPtrOutput) Elem() BranchProtectionRestrictionsOutput {
	return o.ApplyT(func(v *BranchProtectionRestrictions) BranchProtectionRestrictions { return *v }).(BranchProtectionRestrictionsOutput)
}

func (o BranchProtectionRestrictionsPtrOutput) Apps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRestrictions) []string { return v.Apps }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRestrictionsPtrOutput) Teams() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRestrictions) []string { return v.Teams }).(pulumi.StringArrayOutput)
}

func (o BranchProtectionRestrictionsPtrOutput) Users() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BranchProtectionRestrictions) []string { return v.Users }).(pulumi.StringArrayOutput)
}

type OrganizationWebhookConfiguration struct {
	ContentType *string `pulumi:"contentType"`
	InsecureSsl *bool   `pulumi:"insecureSsl"`
	Secret      *string `pulumi:"secret"`
	// URL of the webhook
	Url string `pulumi:"url"`
}

// OrganizationWebhookConfigurationInput is an input type that accepts OrganizationWebhookConfigurationArgs and OrganizationWebhookConfigurationOutput values.
// You can construct a concrete instance of `OrganizationWebhookConfigurationInput` via:
//
// 		 OrganizationWebhookConfigurationArgs{...}
//
type OrganizationWebhookConfigurationInput interface {
	pulumi.Input

	ToOrganizationWebhookConfigurationOutput() OrganizationWebhookConfigurationOutput
	ToOrganizationWebhookConfigurationOutputWithContext(context.Context) OrganizationWebhookConfigurationOutput
}

type OrganizationWebhookConfigurationArgs struct {
	ContentType pulumi.StringPtrInput `pulumi:"contentType"`
	InsecureSsl pulumi.BoolPtrInput   `pulumi:"insecureSsl"`
	Secret      pulumi.StringPtrInput `pulumi:"secret"`
	// URL of the webhook
	Url pulumi.StringInput `pulumi:"url"`
}

func (OrganizationWebhookConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*OrganizationWebhookConfiguration)(nil)).Elem()
}

func (i OrganizationWebhookConfigurationArgs) ToOrganizationWebhookConfigurationOutput() OrganizationWebhookConfigurationOutput {
	return i.ToOrganizationWebhookConfigurationOutputWithContext(context.Background())
}

func (i OrganizationWebhookConfigurationArgs) ToOrganizationWebhookConfigurationOutputWithContext(ctx context.Context) OrganizationWebhookConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationWebhookConfigurationOutput)
}

func (i OrganizationWebhookConfigurationArgs) ToOrganizationWebhookConfigurationPtrOutput() OrganizationWebhookConfigurationPtrOutput {
	return i.ToOrganizationWebhookConfigurationPtrOutputWithContext(context.Background())
}

func (i OrganizationWebhookConfigurationArgs) ToOrganizationWebhookConfigurationPtrOutputWithContext(ctx context.Context) OrganizationWebhookConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationWebhookConfigurationOutput).ToOrganizationWebhookConfigurationPtrOutputWithContext(ctx)
}

// OrganizationWebhookConfigurationPtrInput is an input type that accepts OrganizationWebhookConfigurationArgs, OrganizationWebhookConfigurationPtr and OrganizationWebhookConfigurationPtrOutput values.
// You can construct a concrete instance of `OrganizationWebhookConfigurationPtrInput` via:
//
// 		 OrganizationWebhookConfigurationArgs{...}
//
//  or:
//
// 		 nil
//
type OrganizationWebhookConfigurationPtrInput interface {
	pulumi.Input

	ToOrganizationWebhookConfigurationPtrOutput() OrganizationWebhookConfigurationPtrOutput
	ToOrganizationWebhookConfigurationPtrOutputWithContext(context.Context) OrganizationWebhookConfigurationPtrOutput
}

type organizationWebhookConfigurationPtrType OrganizationWebhookConfigurationArgs

func OrganizationWebhookConfigurationPtr(v *OrganizationWebhookConfigurationArgs) OrganizationWebhookConfigurationPtrInput {
	return (*organizationWebhookConfigurationPtrType)(v)
}

func (*organizationWebhookConfigurationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationWebhookConfiguration)(nil)).Elem()
}

func (i *organizationWebhookConfigurationPtrType) ToOrganizationWebhookConfigurationPtrOutput() OrganizationWebhookConfigurationPtrOutput {
	return i.ToOrganizationWebhookConfigurationPtrOutputWithContext(context.Background())
}

func (i *organizationWebhookConfigurationPtrType) ToOrganizationWebhookConfigurationPtrOutputWithContext(ctx context.Context) OrganizationWebhookConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationWebhookConfigurationPtrOutput)
}

type OrganizationWebhookConfigurationOutput struct{ *pulumi.OutputState }

func (OrganizationWebhookConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*OrganizationWebhookConfiguration)(nil)).Elem()
}

func (o OrganizationWebhookConfigurationOutput) ToOrganizationWebhookConfigurationOutput() OrganizationWebhookConfigurationOutput {
	return o
}

func (o OrganizationWebhookConfigurationOutput) ToOrganizationWebhookConfigurationOutputWithContext(ctx context.Context) OrganizationWebhookConfigurationOutput {
	return o
}

func (o OrganizationWebhookConfigurationOutput) ToOrganizationWebhookConfigurationPtrOutput() OrganizationWebhookConfigurationPtrOutput {
	return o.ToOrganizationWebhookConfigurationPtrOutputWithContext(context.Background())
}

func (o OrganizationWebhookConfigurationOutput) ToOrganizationWebhookConfigurationPtrOutputWithContext(ctx context.Context) OrganizationWebhookConfigurationPtrOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) *OrganizationWebhookConfiguration {
		return &v
	}).(OrganizationWebhookConfigurationPtrOutput)
}
func (o OrganizationWebhookConfigurationOutput) ContentType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) *string { return v.ContentType }).(pulumi.StringPtrOutput)
}

func (o OrganizationWebhookConfigurationOutput) InsecureSsl() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) *bool { return v.InsecureSsl }).(pulumi.BoolPtrOutput)
}

func (o OrganizationWebhookConfigurationOutput) Secret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) *string { return v.Secret }).(pulumi.StringPtrOutput)
}

// URL of the webhook
func (o OrganizationWebhookConfigurationOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) string { return v.Url }).(pulumi.StringOutput)
}

type OrganizationWebhookConfigurationPtrOutput struct{ *pulumi.OutputState }

func (OrganizationWebhookConfigurationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationWebhookConfiguration)(nil)).Elem()
}

func (o OrganizationWebhookConfigurationPtrOutput) ToOrganizationWebhookConfigurationPtrOutput() OrganizationWebhookConfigurationPtrOutput {
	return o
}

func (o OrganizationWebhookConfigurationPtrOutput) ToOrganizationWebhookConfigurationPtrOutputWithContext(ctx context.Context) OrganizationWebhookConfigurationPtrOutput {
	return o
}

func (o OrganizationWebhookConfigurationPtrOutput) Elem() OrganizationWebhookConfigurationOutput {
	return o.ApplyT(func(v *OrganizationWebhookConfiguration) OrganizationWebhookConfiguration { return *v }).(OrganizationWebhookConfigurationOutput)
}

func (o OrganizationWebhookConfigurationPtrOutput) ContentType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) *string { return v.ContentType }).(pulumi.StringPtrOutput)
}

func (o OrganizationWebhookConfigurationPtrOutput) InsecureSsl() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) *bool { return v.InsecureSsl }).(pulumi.BoolPtrOutput)
}

func (o OrganizationWebhookConfigurationPtrOutput) Secret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) *string { return v.Secret }).(pulumi.StringPtrOutput)
}

// URL of the webhook
func (o OrganizationWebhookConfigurationPtrOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v OrganizationWebhookConfiguration) string { return v.Url }).(pulumi.StringOutput)
}

type RepositoryTemplate struct {
	Owner      string `pulumi:"owner"`
	Repository string `pulumi:"repository"`
}

// RepositoryTemplateInput is an input type that accepts RepositoryTemplateArgs and RepositoryTemplateOutput values.
// You can construct a concrete instance of `RepositoryTemplateInput` via:
//
// 		 RepositoryTemplateArgs{...}
//
type RepositoryTemplateInput interface {
	pulumi.Input

	ToRepositoryTemplateOutput() RepositoryTemplateOutput
	ToRepositoryTemplateOutputWithContext(context.Context) RepositoryTemplateOutput
}

type RepositoryTemplateArgs struct {
	Owner      pulumi.StringInput `pulumi:"owner"`
	Repository pulumi.StringInput `pulumi:"repository"`
}

func (RepositoryTemplateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RepositoryTemplate)(nil)).Elem()
}

func (i RepositoryTemplateArgs) ToRepositoryTemplateOutput() RepositoryTemplateOutput {
	return i.ToRepositoryTemplateOutputWithContext(context.Background())
}

func (i RepositoryTemplateArgs) ToRepositoryTemplateOutputWithContext(ctx context.Context) RepositoryTemplateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryTemplateOutput)
}

func (i RepositoryTemplateArgs) ToRepositoryTemplatePtrOutput() RepositoryTemplatePtrOutput {
	return i.ToRepositoryTemplatePtrOutputWithContext(context.Background())
}

func (i RepositoryTemplateArgs) ToRepositoryTemplatePtrOutputWithContext(ctx context.Context) RepositoryTemplatePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryTemplateOutput).ToRepositoryTemplatePtrOutputWithContext(ctx)
}

// RepositoryTemplatePtrInput is an input type that accepts RepositoryTemplateArgs, RepositoryTemplatePtr and RepositoryTemplatePtrOutput values.
// You can construct a concrete instance of `RepositoryTemplatePtrInput` via:
//
// 		 RepositoryTemplateArgs{...}
//
//  or:
//
// 		 nil
//
type RepositoryTemplatePtrInput interface {
	pulumi.Input

	ToRepositoryTemplatePtrOutput() RepositoryTemplatePtrOutput
	ToRepositoryTemplatePtrOutputWithContext(context.Context) RepositoryTemplatePtrOutput
}

type repositoryTemplatePtrType RepositoryTemplateArgs

func RepositoryTemplatePtr(v *RepositoryTemplateArgs) RepositoryTemplatePtrInput {
	return (*repositoryTemplatePtrType)(v)
}

func (*repositoryTemplatePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryTemplate)(nil)).Elem()
}

func (i *repositoryTemplatePtrType) ToRepositoryTemplatePtrOutput() RepositoryTemplatePtrOutput {
	return i.ToRepositoryTemplatePtrOutputWithContext(context.Background())
}

func (i *repositoryTemplatePtrType) ToRepositoryTemplatePtrOutputWithContext(ctx context.Context) RepositoryTemplatePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryTemplatePtrOutput)
}

type RepositoryTemplateOutput struct{ *pulumi.OutputState }

func (RepositoryTemplateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RepositoryTemplate)(nil)).Elem()
}

func (o RepositoryTemplateOutput) ToRepositoryTemplateOutput() RepositoryTemplateOutput {
	return o
}

func (o RepositoryTemplateOutput) ToRepositoryTemplateOutputWithContext(ctx context.Context) RepositoryTemplateOutput {
	return o
}

func (o RepositoryTemplateOutput) ToRepositoryTemplatePtrOutput() RepositoryTemplatePtrOutput {
	return o.ToRepositoryTemplatePtrOutputWithContext(context.Background())
}

func (o RepositoryTemplateOutput) ToRepositoryTemplatePtrOutputWithContext(ctx context.Context) RepositoryTemplatePtrOutput {
	return o.ApplyT(func(v RepositoryTemplate) *RepositoryTemplate {
		return &v
	}).(RepositoryTemplatePtrOutput)
}
func (o RepositoryTemplateOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v RepositoryTemplate) string { return v.Owner }).(pulumi.StringOutput)
}

func (o RepositoryTemplateOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v RepositoryTemplate) string { return v.Repository }).(pulumi.StringOutput)
}

type RepositoryTemplatePtrOutput struct{ *pulumi.OutputState }

func (RepositoryTemplatePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryTemplate)(nil)).Elem()
}

func (o RepositoryTemplatePtrOutput) ToRepositoryTemplatePtrOutput() RepositoryTemplatePtrOutput {
	return o
}

func (o RepositoryTemplatePtrOutput) ToRepositoryTemplatePtrOutputWithContext(ctx context.Context) RepositoryTemplatePtrOutput {
	return o
}

func (o RepositoryTemplatePtrOutput) Elem() RepositoryTemplateOutput {
	return o.ApplyT(func(v *RepositoryTemplate) RepositoryTemplate { return *v }).(RepositoryTemplateOutput)
}

func (o RepositoryTemplatePtrOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v RepositoryTemplate) string { return v.Owner }).(pulumi.StringOutput)
}

func (o RepositoryTemplatePtrOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v RepositoryTemplate) string { return v.Repository }).(pulumi.StringOutput)
}

type RepositoryWebhookConfiguration struct {
	ContentType *string `pulumi:"contentType"`
	InsecureSsl *bool   `pulumi:"insecureSsl"`
	Secret      *string `pulumi:"secret"`
	// URL of the webhook
	Url string `pulumi:"url"`
}

// RepositoryWebhookConfigurationInput is an input type that accepts RepositoryWebhookConfigurationArgs and RepositoryWebhookConfigurationOutput values.
// You can construct a concrete instance of `RepositoryWebhookConfigurationInput` via:
//
// 		 RepositoryWebhookConfigurationArgs{...}
//
type RepositoryWebhookConfigurationInput interface {
	pulumi.Input

	ToRepositoryWebhookConfigurationOutput() RepositoryWebhookConfigurationOutput
	ToRepositoryWebhookConfigurationOutputWithContext(context.Context) RepositoryWebhookConfigurationOutput
}

type RepositoryWebhookConfigurationArgs struct {
	ContentType pulumi.StringPtrInput `pulumi:"contentType"`
	InsecureSsl pulumi.BoolPtrInput   `pulumi:"insecureSsl"`
	Secret      pulumi.StringPtrInput `pulumi:"secret"`
	// URL of the webhook
	Url pulumi.StringInput `pulumi:"url"`
}

func (RepositoryWebhookConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RepositoryWebhookConfiguration)(nil)).Elem()
}

func (i RepositoryWebhookConfigurationArgs) ToRepositoryWebhookConfigurationOutput() RepositoryWebhookConfigurationOutput {
	return i.ToRepositoryWebhookConfigurationOutputWithContext(context.Background())
}

func (i RepositoryWebhookConfigurationArgs) ToRepositoryWebhookConfigurationOutputWithContext(ctx context.Context) RepositoryWebhookConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryWebhookConfigurationOutput)
}

func (i RepositoryWebhookConfigurationArgs) ToRepositoryWebhookConfigurationPtrOutput() RepositoryWebhookConfigurationPtrOutput {
	return i.ToRepositoryWebhookConfigurationPtrOutputWithContext(context.Background())
}

func (i RepositoryWebhookConfigurationArgs) ToRepositoryWebhookConfigurationPtrOutputWithContext(ctx context.Context) RepositoryWebhookConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryWebhookConfigurationOutput).ToRepositoryWebhookConfigurationPtrOutputWithContext(ctx)
}

// RepositoryWebhookConfigurationPtrInput is an input type that accepts RepositoryWebhookConfigurationArgs, RepositoryWebhookConfigurationPtr and RepositoryWebhookConfigurationPtrOutput values.
// You can construct a concrete instance of `RepositoryWebhookConfigurationPtrInput` via:
//
// 		 RepositoryWebhookConfigurationArgs{...}
//
//  or:
//
// 		 nil
//
type RepositoryWebhookConfigurationPtrInput interface {
	pulumi.Input

	ToRepositoryWebhookConfigurationPtrOutput() RepositoryWebhookConfigurationPtrOutput
	ToRepositoryWebhookConfigurationPtrOutputWithContext(context.Context) RepositoryWebhookConfigurationPtrOutput
}

type repositoryWebhookConfigurationPtrType RepositoryWebhookConfigurationArgs

func RepositoryWebhookConfigurationPtr(v *RepositoryWebhookConfigurationArgs) RepositoryWebhookConfigurationPtrInput {
	return (*repositoryWebhookConfigurationPtrType)(v)
}

func (*repositoryWebhookConfigurationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryWebhookConfiguration)(nil)).Elem()
}

func (i *repositoryWebhookConfigurationPtrType) ToRepositoryWebhookConfigurationPtrOutput() RepositoryWebhookConfigurationPtrOutput {
	return i.ToRepositoryWebhookConfigurationPtrOutputWithContext(context.Background())
}

func (i *repositoryWebhookConfigurationPtrType) ToRepositoryWebhookConfigurationPtrOutputWithContext(ctx context.Context) RepositoryWebhookConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryWebhookConfigurationPtrOutput)
}

type RepositoryWebhookConfigurationOutput struct{ *pulumi.OutputState }

func (RepositoryWebhookConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RepositoryWebhookConfiguration)(nil)).Elem()
}

func (o RepositoryWebhookConfigurationOutput) ToRepositoryWebhookConfigurationOutput() RepositoryWebhookConfigurationOutput {
	return o
}

func (o RepositoryWebhookConfigurationOutput) ToRepositoryWebhookConfigurationOutputWithContext(ctx context.Context) RepositoryWebhookConfigurationOutput {
	return o
}

func (o RepositoryWebhookConfigurationOutput) ToRepositoryWebhookConfigurationPtrOutput() RepositoryWebhookConfigurationPtrOutput {
	return o.ToRepositoryWebhookConfigurationPtrOutputWithContext(context.Background())
}

func (o RepositoryWebhookConfigurationOutput) ToRepositoryWebhookConfigurationPtrOutputWithContext(ctx context.Context) RepositoryWebhookConfigurationPtrOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) *RepositoryWebhookConfiguration {
		return &v
	}).(RepositoryWebhookConfigurationPtrOutput)
}
func (o RepositoryWebhookConfigurationOutput) ContentType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) *string { return v.ContentType }).(pulumi.StringPtrOutput)
}

func (o RepositoryWebhookConfigurationOutput) InsecureSsl() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) *bool { return v.InsecureSsl }).(pulumi.BoolPtrOutput)
}

func (o RepositoryWebhookConfigurationOutput) Secret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) *string { return v.Secret }).(pulumi.StringPtrOutput)
}

// URL of the webhook
func (o RepositoryWebhookConfigurationOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) string { return v.Url }).(pulumi.StringOutput)
}

type RepositoryWebhookConfigurationPtrOutput struct{ *pulumi.OutputState }

func (RepositoryWebhookConfigurationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryWebhookConfiguration)(nil)).Elem()
}

func (o RepositoryWebhookConfigurationPtrOutput) ToRepositoryWebhookConfigurationPtrOutput() RepositoryWebhookConfigurationPtrOutput {
	return o
}

func (o RepositoryWebhookConfigurationPtrOutput) ToRepositoryWebhookConfigurationPtrOutputWithContext(ctx context.Context) RepositoryWebhookConfigurationPtrOutput {
	return o
}

func (o RepositoryWebhookConfigurationPtrOutput) Elem() RepositoryWebhookConfigurationOutput {
	return o.ApplyT(func(v *RepositoryWebhookConfiguration) RepositoryWebhookConfiguration { return *v }).(RepositoryWebhookConfigurationOutput)
}

func (o RepositoryWebhookConfigurationPtrOutput) ContentType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) *string { return v.ContentType }).(pulumi.StringPtrOutput)
}

func (o RepositoryWebhookConfigurationPtrOutput) InsecureSsl() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) *bool { return v.InsecureSsl }).(pulumi.BoolPtrOutput)
}

func (o RepositoryWebhookConfigurationPtrOutput) Secret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) *string { return v.Secret }).(pulumi.StringPtrOutput)
}

// URL of the webhook
func (o RepositoryWebhookConfigurationPtrOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v RepositoryWebhookConfiguration) string { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(BranchProtectionRequiredPullRequestReviewsOutput{})
	pulumi.RegisterOutputType(BranchProtectionRequiredPullRequestReviewsPtrOutput{})
	pulumi.RegisterOutputType(BranchProtectionRequiredStatusChecksOutput{})
	pulumi.RegisterOutputType(BranchProtectionRequiredStatusChecksPtrOutput{})
	pulumi.RegisterOutputType(BranchProtectionRestrictionsOutput{})
	pulumi.RegisterOutputType(BranchProtectionRestrictionsPtrOutput{})
	pulumi.RegisterOutputType(OrganizationWebhookConfigurationOutput{})
	pulumi.RegisterOutputType(OrganizationWebhookConfigurationPtrOutput{})
	pulumi.RegisterOutputType(RepositoryTemplateOutput{})
	pulumi.RegisterOutputType(RepositoryTemplatePtrOutput{})
	pulumi.RegisterOutputType(RepositoryWebhookConfigurationOutput{})
	pulumi.RegisterOutputType(RepositoryWebhookConfigurationPtrOutput{})
}
