// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package github

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// Provides a GitHub user's GPG key resource.
//
// This resource allows you to add/remove GPG keys from your user account.
type UserGPGKey struct {
	pulumi.CustomResourceState

	// Your public GPG key, generated in ASCII-armored format.
	// See [Generating a new GPG key](https://help.github.com/articles/generating-a-new-gpg-key/) for help on creating a GPG key.
	ArmoredPublicKey pulumi.StringOutput `pulumi:"armoredPublicKey"`
	Etag             pulumi.StringOutput `pulumi:"etag"`
	// The key ID of the GPG key, e.g. `3262EFF25BA0D270`
	KeyId pulumi.StringOutput `pulumi:"keyId"`
}

// NewUserGPGKey registers a new resource with the given unique name, arguments, and options.
func NewUserGPGKey(ctx *pulumi.Context,
	name string, args *UserGPGKeyArgs, opts ...pulumi.ResourceOption) (*UserGPGKey, error) {
	if args == nil || args.ArmoredPublicKey == nil {
		return nil, errors.New("missing required argument 'ArmoredPublicKey'")
	}
	if args == nil {
		args = &UserGPGKeyArgs{}
	}
	var resource UserGPGKey
	err := ctx.RegisterResource("github:index/userGPGKey:UserGPGKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUserGPGKey gets an existing UserGPGKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUserGPGKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserGPGKeyState, opts ...pulumi.ResourceOption) (*UserGPGKey, error) {
	var resource UserGPGKey
	err := ctx.ReadResource("github:index/userGPGKey:UserGPGKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UserGPGKey resources.
type userGPGKeyState struct {
	// Your public GPG key, generated in ASCII-armored format.
	// See [Generating a new GPG key](https://help.github.com/articles/generating-a-new-gpg-key/) for help on creating a GPG key.
	ArmoredPublicKey *string `pulumi:"armoredPublicKey"`
	Etag             *string `pulumi:"etag"`
	// The key ID of the GPG key, e.g. `3262EFF25BA0D270`
	KeyId *string `pulumi:"keyId"`
}

type UserGPGKeyState struct {
	// Your public GPG key, generated in ASCII-armored format.
	// See [Generating a new GPG key](https://help.github.com/articles/generating-a-new-gpg-key/) for help on creating a GPG key.
	ArmoredPublicKey pulumi.StringPtrInput
	Etag             pulumi.StringPtrInput
	// The key ID of the GPG key, e.g. `3262EFF25BA0D270`
	KeyId pulumi.StringPtrInput
}

func (UserGPGKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*userGPGKeyState)(nil)).Elem()
}

type userGPGKeyArgs struct {
	// Your public GPG key, generated in ASCII-armored format.
	// See [Generating a new GPG key](https://help.github.com/articles/generating-a-new-gpg-key/) for help on creating a GPG key.
	ArmoredPublicKey string `pulumi:"armoredPublicKey"`
}

// The set of arguments for constructing a UserGPGKey resource.
type UserGPGKeyArgs struct {
	// Your public GPG key, generated in ASCII-armored format.
	// See [Generating a new GPG key](https://help.github.com/articles/generating-a-new-gpg-key/) for help on creating a GPG key.
	ArmoredPublicKey pulumi.StringInput
}

func (UserGPGKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userGPGKeyArgs)(nil)).Elem()
}
