// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package getmembership

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetMembership(ctx *pulumi.Context, args *GetMembershipArgs, opts ...pulumi.InvokeOption) (*GetMembershipResult, error) {
	var rv GetMembershipResult
	err := ctx.Invoke("github:index/getmembership/getMembership:getMembership", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMembership.
type GetMembershipArgs struct {
	// The username to lookup in the organization.
	Username string `pulumi:"username"`
}

// A collection of values returned by getMembership.
type GetMembershipResult struct {
	// An etag representing the membership object.
	Etag string `pulumi:"etag"`
	// id is the provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// `admin` or `member` -- the role the user has within the organization.
	Role string `pulumi:"role"`
	// The username.
	Username string `pulumi:"username"`
}
