// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GitHub.index/getIPRanges
{
    public static class GetIPRanges
    {
        /// <summary>
        /// {{% examples %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetIPRangesResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetIPRangesResult>("github:index/getipranges/getIPRanges:getIPRanges", InvokeArgs.Empty, options.WithVersion());
    }


    [OutputType]
    public sealed class GetIPRangesResult
    {
        /// <summary>
        /// An Array of IP addresses in CIDR format specifying the Git servers.
        /// </summary>
        public readonly ImmutableArray<string> Gits;
        /// <summary>
        /// An Array of IP addresses in CIDR format specifying the addresses that incoming service hooks will originate from.
        /// </summary>
        public readonly ImmutableArray<string> Hooks;
        /// <summary>
        /// id is the provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// An Array of IP addresses in CIDR format specifying the A records for GitHub Importer.
        /// </summary>
        public readonly ImmutableArray<string> Importers;
        /// <summary>
        /// An Array of IP addresses in CIDR format specifying the A records for GitHub Pages.
        /// </summary>
        public readonly ImmutableArray<string> Pages;

        [OutputConstructor]
        private GetIPRangesResult(
            ImmutableArray<string> gits,

            ImmutableArray<string> hooks,

            string id,

            ImmutableArray<string> importers,

            ImmutableArray<string> pages)
        {
            Gits = gits;
            Hooks = hooks;
            Id = id;
            Importers = importers;
            Pages = pages;
        }
    }
}
