// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as outputs from "../types/output";

export interface BranchProtectionRequiredPullRequestReviews {
    dismissStaleReviews?: boolean;
    dismissalTeams?: string[];
    dismissalUsers?: string[];
    includeAdmins?: boolean;
    requireCodeOwnerReviews?: boolean;
    requiredApprovingReviewCount?: number;
}

export interface BranchProtectionRequiredStatusChecks {
    contexts?: string[];
    includeAdmins?: boolean;
    strict?: boolean;
}

export interface BranchProtectionRestrictions {
    apps?: string[];
    teams?: string[];
    users?: string[];
}

export interface OrganizationWebhookConfiguration {
    contentType?: string;
    insecureSsl?: boolean;
    secret?: string;
    /**
     * URL of the webhook
     */
    url: string;
}

export interface RepositoryTemplate {
    owner: string;
    repository: string;
}

export interface RepositoryWebhookConfiguration {
    contentType?: string;
    insecureSsl?: boolean;
    secret?: string;
    /**
     * URL of the webhook
     */
    url: string;
}
