// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package getteam

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// Use this data source to retrieve information about a GitHub team.
func GetTeam(ctx *pulumi.Context, args *GetTeamArgs, opts ...pulumi.InvokeOption) (*GetTeamResult, error) {
	var rv GetTeamResult
	err := ctx.Invoke("github:index/getteam/getTeam:getTeam", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTeam.
type GetTeamArgs struct {
	// The team slug.
	Slug string `pulumi:"slug"`
}

// A collection of values returned by getTeam.
type GetTeamResult struct {
	// the team's description.
	Description string `pulumi:"description"`
	// id is the provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// List of team members
	Members []string `pulumi:"members"`
	// the team's full name.
	Name   string `pulumi:"name"`
	NodeId string `pulumi:"nodeId"`
	// the team's permission level.
	Permission string `pulumi:"permission"`
	// the team's privacy type.
	Privacy string `pulumi:"privacy"`
	Slug    string `pulumi:"slug"`
}
