name: build
on:
  pull_request:
    branches:
      - master

env:
  ORG: timmyers

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Install tf2pulumi
        uses: pulumi/action-install-tf2pulumi@releases/v1
        with:
          tf2pulumi-version: 0.6.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Ensure dependencies
        run: make ensure
      - name: Generate provider deps
        run: make provider
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build SDK
        run: make build_node
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Install tf2pulumi
        uses: pulumi/action-install-tf2pulumi@releases/v1
        with:
          tf2pulumi-version: 0.6.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Ensure dependencies
        run: make ensure
      - name: Generate provider deps
        run: make provider
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build SDK
        run: make build_python
  dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Install tf2pulumi
        uses: pulumi/action-install-tf2pulumi@releases/v1
        with:
          tf2pulumi-version: 0.6.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Ensure dependencies
        run: make ensure
      - name: Generate provider deps
        run: make provider
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.201'
      - name: Build SDK
        run: make build_dotnet
  provider:
    runs-on: ubuntu-latest
    steps:
      - name: Install tf2pulumi
        uses: pulumi/action-install-tf2pulumi@releases/v1
        with:
          tf2pulumi-version: 0.6.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Ensure dependencies
        run: make ensure
      - name: Generate provider deps
        run: make provider
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.129.0
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
